Pool 2870 update prizepool vault to be able to redistribute prizes
pooltogether/v5-vault pull request #14
Opened 2023-06-28 21:08 UTC by asselstine

2023-06-28 21:09 UTC, asselstine commented
Note: compilation was having trouble so I also removed the dependency on the claimer

2023-07-04 18:18 UTC, trmid requested changes
Added some suggestions for name changes on the hook struct to make it less repetitive.

2023-07-04 18:18 UTC, trmid commented on src/interfaces/IVaultHooks.sol
> +}
It's odd having `Hook.hooks` as a field. We could do something like:
```suggestion
struct VaultHooks {
    /// @notice If true, the vault will call the beforeClaimPrize fxn on the hook.
    bool useBeforeClaimPrize;
    /// @notice If true, the vault will call the afterClaimPrize on the hook
    bool useAfterClaimPrize;
    /// @notice The address of the smart contract implementing the hooks
    IVaultHooks implementation;
}
```

2023-07-04 18:18 UTC, trmid commented on src/Vault.sol
> +    }
`hook.hooks` is a bit odd. We could change it to:
```suggestion
    VaultHooks memory hooks = _hooks[_winner];
    address recipient;
    if (hooks.useBeforeClaimPrize) {
      recipient = hooks.implementation.beforeClaimPrize(_winner, _tier, _prizeIndex);
    } else {
      recipient = _winner;
    }

    uint prizeTotal = _prizePool.claimPrize(_winner, _tier, _prizeIndex, recipient, _fee, _feeRecipient);

    if (hooks.useAfterClaimPrize) {
      hooks.implementation.afterClaimPrize(_winner, _tier, _prizeIndex, prizeTotal - _fee, recipient);
    }
```

2023-07-04 19:29 UTC, trmid approved these changes

2023-07-04 20:30 UTC, merged